import type { Anomaly, ChartSpec, ChatMessage, Insight, Summary } from "@/types";

export function generateMarkdownReport(
  summary: Summary | null,
  insights: Insight[],
  anomalies: Anomaly[],
  charts: ChartSpec[],
  messages: ChatMessage[],
): string {
  const lines: string[] = [];

  if (summary) {
    lines.push(`# ${summary.title}`, "");
    lines.push(summary.description, "");
    lines.push(
      `- **Rows:** ${summary.rowCount}`,
      `- **Columns:** ${summary.columnCount}`,
      `- **Data Quality:** ${summary.dataQuality}`,
    );
    if (summary.timeRange) lines.push(`- **Time Range:** ${summary.timeRange}`);
    lines.push("");
  }

  if (insights.length > 0) {
    lines.push("## Key Insights", "");
    for (const insight of insights) {
      const badge = insight.importance === "high" ? "**[HIGH]**" : "";
      lines.push(`- ${badge} ${insight.text}`);
    }
    lines.push("");
  }

  if (anomalies.length > 0) {
    lines.push("## Data Quality Issues", "");
    for (const a of anomalies) {
      lines.push(
        `- **${a.column}** (${a.severity}): ${a.issue}${a.affectedRows ? ` — ${a.affectedRows} rows` : ""}`,
      );
    }
    lines.push("");
  }

  if (charts.length > 0) {
    lines.push("## Suggested Visualizations", "");
    for (const chart of charts) {
      lines.push(`### ${chart.title}`);
      lines.push(`- Type: ${chart.type}`);
      lines.push(`- X: ${chart.xColumn}, Y: ${chart.yColumn}`);
      if (chart.groupBy) lines.push(`- Group by: ${chart.groupBy}`);
      if (chart.description) lines.push(`- ${chart.description}`);
      lines.push("");
    }
  }

  if (messages.length > 0) {
    lines.push("## Q&A Conversation", "");
    for (const msg of messages) {
      const label = msg.role === "user" ? "**You**" : "**DataPilot**";
      lines.push(`${label}: ${msg.content}`, "");
    }
  }

  lines.push("---", "*Generated by DataPilot — AI Data Analyst*");
  return lines.join("\n");
}

export function downloadMarkdown(content: string, filename: string): void {
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
